version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: triangle-pos
    container_name: triangle_app
    restart: unless-stopped
    ports:
      - "80:80"
    environment:
      APP_NAME: "Triangle POS"
      APP_ENV: production
      APP_KEY: ${APP_KEY}
      APP_DEBUG: "false"
      APP_URL: "http://${VPS_IP}"
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}

volumes:
  db_data:
